---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: opencloud-secret
    template:
      data:
        OC_OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        PROXY_OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        PROXY_OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        WEB_OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        IDM_ADMIN_PASSWORD: "{{ .IDM_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: opencloud
