# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.40.2@sha256:18afa43e911f1dff18c7d1eb452361876d9702bb1cdff5c5d75c69617a4065c9
  networkPolicyEnabled: false
  replicas: 1
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      memory: 256Mi
  serviceSpec:
    annotations:
      gatus.home-operations.com/endpoint: |-
        group: services
        interval: 15s
        conditions:
          - "[CONNECTED] == true"
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=1
    - --default_lua_flags=allow-undeclared-keys
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          divisor: 1Mi
          resource: limits.memory
