---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: data
spec:
  allowedNamespaces:
    all: true
  backend:
    s3:
      auth:
        secretRef:
          name: kopiur-repository-secret
          namespace: kopiur-system
      bucket: kopiur
      endpoint: 192.168.3.3:9000
      region: ap-southeast-2
      tls:
        disableTls: true
  encryption:
    passwordSecretRef:
      name: kopiur-repository-secret
      namespace: kopiur-system
      key: KOPIA_PASSWORD
  scheduleDefaults:
    timezone: Australia/Melbourne
