---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6@sha256:53be6d727c7b3cf0df2b147f7ce7cdd31d37fd285314294871a4ccc3837b6872
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 8Gi
    storageClass: longhorn
  superuserSecret:
    name: cloudnative-pg-secret
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 4Gi
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://cnpg/v16/
      endpointURL: https://s3.us-east-005.backblazeb2.com
      # Note: serverName version needs to be incremented
      # when recovering from an existing cnpg cluster
      serverName: postgres-v1
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cloudnative-pg-secret
          key: AWS_SECRET_ACCESS_KEY
  # Note: previousCluster needs to be set to the name of the previous
  # cluster when recovering from an existing cnpg cluster
  #bootstrap:
  #  recovery:
  #    source: &previousCluster postgres-v0
  # Note: externalClusters is needed when recovering from an existing cnpg cluster
  externalClusters:
    - name: &previousCluster postgres-v0
      barmanObjectStore:
        <<: *barmanObjectStore
        serverName: *previousCluster
