---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
spec:
  chartRef:
    kind: OCIRepository
    name: paperless
  interval: 1h
  values:
    controllers:
      paperless:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.20.13@sha256:4b05bcd28e6923768000b5d247cbf2c66fd49bdc3f3b05955bd4f6790a638b01
            env:
              EMPTY_TRASH_DELAY: 0 1 * * *
              PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
              PAPERLESS_BIND_ADDR: 0.0.0.0
              PAPERLESS_DISABLE_REGULAR_LOGIN: true
              PAPERLESS_PORT: &port 80
              PAPERLESS_REDIRECT_LOGIN_TO_SSO: true
              PAPERLESS_REDIS: redis://dragonfly.databases.svc.cluster.local:6379/3
              PAPERLESS_TIKA_ENABLED: 1
              PAPERLESS_TIKA_ENDPOINT: http://localhost:9998
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://localhost:3000
              PAPERLESS_TIME_ZONE: Australia/Melbourne
              PAPERLESS_URL: https://paperless.hyde.services
              USERMAP_GID: 1000
              USERMAP_UID: 1000
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              # E: List directory /var/lib/apt/lists/partial is missing. - Acquire (30: Read-only file system)
              readOnlyRootFilesystem: false
              # E: setgroups 65534 failed - setgroups (1: Operation not permitted)
              #capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 1Gi
              limits:
                memory: 4Gi
          tika:
            image:
              repository: docker.io/apache/tika
              tag: 3.3.0.0@sha256:2a565f1ea1290bdcb74a7d35957d16a989ed44ef98790dcdcc28121d728fa583
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
          gotenberg:
            image:
              repository: docker.io/gotenberg/gotenberg
              tag: 8.29.1@sha256:36c925776fa0db0fd1030408d131fde7ac3453027a559883555155b72adb16a7
            command:
              - /usr/bin/gotenberg
            args:
              - --chromium-disable-javascript=true
              - "--chromium-allow-list=file:///tmp/.*"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.hyde.services"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          paperless:
            app:
              - path: /usr/src/paperless/data
      media:
        type: nfs
        server: 192.168.42.20
        path: /mnt/Fast/Public/Paperless/media
        advancedMounts:
          paperless:
            app:
              - path: /usr/src/paperless/media
      tmp:
        type: emptyDir
